# Generated by Django 4.2.5 on 2023-09-27 07:36

import core.models.Product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Product.generate_image_filename),
        ),
    ]
